name: Lint & Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff
      - name: Lint lambda
        run: |
          if [ -f "lambda/lambda_function.py" ]; then
            ruff check lambda/lambda_function.py
          else
            echo "lambda/lambda_function.py not found."
          fi

  repo-sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure key paths exist
        run: |
          test -d lambda || (echo "Missing lambda/ dir" && exit 1)
          test -d frontend || (echo "Missing frontend/ dir" && exit 1)
          test -d docs || (echo "Missing docs/ dir" && exit 1)
